baseURL = "https://gubanov.site/"
title = "By Gaben"
languageCode = "ru-ru"
theme = "hello-abyss"

[pagination]
pagerSize = 10

enableRobotsTXT = true
enableEmoji = true
disableSitemap = false
disable404 = false

[params]
author = ["Gubanov Danil"]
dateform = "Jan 2, 2006"
dateformShort = "Jan 2"
dateformNum = "01.02.2006"
dateformNumTime = "15:04 01.02.2006"
homeSubtitle = "Welcome to gubanov.site"
disableReadOtherPosts = false
defaultTheme = "dark"
enableSharingButtons = true
enableSlickSlider = true
enableThemeToggle = true
description = "Blog gubanov.site in IT"
keywords = "IT, information, hacks, works, homepage, blog"

[params.footer]
trademark = false
author = false
copyright = false
rss = false

[[params.social]]
name = "telegram"
url = "https://t.me/gubanovdanil"

[[params.social]]
name = "email"
url = "mailto:gubanov.code@gmail.com"

[[params.social]]
name = "github"
url = "https://github.com/maintainer64"

[[params.social]]
name = "gitlab"
url = "https://gitlab.com/gabenD"

[taxonomies]
category = "blog"
tag = "tags"
series = "series"

[languages.en]
title = "Добрый день!"
subtitle = "Добро пожаловать на сайт мой сайт"
keywords = ""
copyright = '<a href="/" target="_blank" rel="noopener"></a>'
readOtherPosts = "Read other posts"

[languages.en.params.logo]
logoText = "$ cd /home/"
logoHomeLink = "/"

[[menu.main]]
identifier = "blog"
name = " Blog"
url = "/posts"

[outputs]
home = ["HTML", "RSS"]
