releasePrefix: "-"

defaultImage: docker.io/maintainer64/personal-site
defaultImageTag: ""

generic:
  usePredefinedAffinity: false

ingresses:
  gubanov.site:
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - paths:
          - serviceName: front
            servicePort: http
    extraTls:
      - hosts:
          - gubanov.site
        secretName: "front-tls"
  www.gubanov.site:
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - paths:
          - serviceName: front
            servicePort: http
    extraTls:
      - hosts:
          - www.gubanov.site
        secretName: "front-tls-www"

services:
  front:
    ports:
      - name: http
        protocol: TCP
        port: 80
        targetPort: http

deployments:
  front:
    replicas: 1
    containers:
      - name: front
        ports:
          - name: http
            containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        startupProbe:
          httpGet:
            path: /
            port: http
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 12
        livenessProbe:
          httpGet:
            path: /
            port: http
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 6
        readinessProbe:
          httpGet:
            path: /
            port: http
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 2