{{- if or ($.Capabilities.APIVersions.Has "traefik.io/v1alpha1") ($.Capabilities.APIVersions.Has "traefik.containo.us/v1alpha1") }}
{{- range $name, $middlewares := .Values.middlewares }}
---
kind: Middleware
apiVersion: {{ include "helpers.capabilities.traefik.apiVersion" $ }}
metadata:
  name: {{ include "helpers.app.fullname" (dict "name" $name "context" $) }}
  labels:
    {{- include "helpers.app.labels" $ | nindent 4 }}
spec:
    {{- include "helpers.tplvalues.render" ( dict "value" . "context" $ ) | nindent 2 }}
{{- end }}
{{- end }}

{{- if or ($.Capabilities.APIVersions.Has "traefik.io/v1alpha1") ($.Capabilities.APIVersions.Has "traefik.containo.us/v1alpha1") }}
{{- range $name, $middlewares := .Values.middlewaresTCP }}
---
kind: MiddlewareTCP
apiVersion: {{ include "helpers.capabilities.traefik.apiVersion" $ }}
metadata:
  name: {{ include "helpers.app.fullname" (dict "name" $name "context" $) }}
  labels:
    {{- include "helpers.app.labels" $ | nindent 4 }}
spec:
    {{- include "helpers.tplvalues.render" ( dict "value" . "context" $ ) | nindent 2 }}
{{- end }}
{{- end }}